site_name: Development Notes for Johan Martin
repo_url: https://github.com/catenare/devnotes
site_description: Notes tracking for developing different apps.
site_author: Johan Martin (http://www.johan-martin.com)
repo_name: 'GitHub'
edit_uri: edit/master/md/
# docs_dir: 'md'
# site_dir: 'docs'
copyright: Johan Martin &copy; 2017
markdown_extensions:
  - pymdownx.tilde
theme: 'material'
pages:
- Home: 'index.md'
- Sections:
  - Database: 
      - Postgresql: 'database.md'
      - Migrations: 'dbmigrations.md'
  - Reports: 'reporting.md'
  - Mobile:
    - 'Mobile Dev': 'mobile.md'
  - Languages:
    - 'PHP': 'php.md'
    - 'Python': 'python.md'
    - 'Ruby': 'ruby.md'
  - Frameworks:
    - 'Spring': 'spring.md'
  - Version Control:
    - 'Git': 'git.md'
  - 'Web Development':
    - 'Front-End': 'front.md'
  - Research: 'research.md'
  - Documentation: 'docs.md'
  - 'Other': 'other.md'


