site_name: Development Notes for Johan Martin
repo_url: https://github.com/catenare/devnotes
site_description: Notes tracking for developing different apps.
site_author: Johan Martin (http://www.johan-martin.com)
repo_name: 'GitHub'
edit_uri: edit/master/md/
dev_addr: '127.0.0.1:8888'
strict: true
# docs_dir: 'md'
# site_dir: 'docs'
copyright: Johan Martin &copy; 2017
markdown_extensions:
  - pymdownx.tilde
theme: 'material'
extra_css:
- css/extra.css
pages:
- Home: 'index.md'
- Development:
  - Wordpress:
    - API:
      - API: 'php/wordpress/api/api.md'
      - 'Angular': 'php/wordpress/api/angular.md'
      - 'Vuejs': 'php/wordpress/api/vuejs.md'
    - 'Setup': 'php/wordpress/setup.md'
    - 'Local Dev': 'php/wordpress/dev.md'
    - 'Plugin Dev': 'php/wordpress/plugin development.md'
    - 'Theme Dev': 'php/wordpress/themes.md'
  - Database: 
      - Postgresql: 'database.md'
      - Migrations: 'dbmigrations.md'
  - Web:
    - 'Basic Setup': 'web/page.md'
    - 'Front End':
      - 'Foundation': 'web/foundation.md'
      - 'Static': 'web/static.md'
      - 'Front': 'web/front.md'
      - 'CSS': 'web/css.md'
    - 'Build Tools':
      - 'Webpack':
        - 'Notes': 'web/javascript/webpack/notes.md'
        - 'Configuration': 
          - 'Basic': 'web/javascript/webpack/webpack.md'
          - 'html-webpack-plugin': 'web/javascript/webpack/html-webpack-plugin.md'
  - JavaScript:
    - 'General Notes': 'web/notes.md'
    - 'JS Starter Config': 'web/javascript/startup.md'
    - 'RxJs': 'web/javascript/rxjs.md'
    - Angular:
      - 'Learning Angular': 'web/javascript/angular.md'
    - 'Vuejs':
      - 'notes': 'web/javascript/vue/notes.md' 
      - 'Vuejs': 'web/javascript/vue/vuejs.md'
      - 'Vuejs Setup': 'web/javascript/vue/configuration.md'
      - 'Foundation Setup': 'web/javascript/vue/foundation.md'
  - PHP:
    - Resources: 'php/resources.md'
    - Composer: 'php/composer.md'
  - 'Python': 
    - 'General': 'python/general.md'
    - 'Packages': 'python/packages.md'
    # - 'Research': 'python/research.md'
  - 'Ruby': 'ruby.md'
  - 'Java': 'java.md'
  - Frameworks:
    - Spring: 'spring.md'
  - Version Control:
    - 'Git': 'git.md'
  - Mobile:
    - General: 'mobile/general.md'
    - Research: 'mobile/mobile.md'
    - 'Mobile Dev Notes': 'mobile/mobilenotes.md'
    - Ionic: 'mobile/ionic.md'
- "Content Management": 'cms.md'
- Tools:
  - Reporting: 'reporting.md'
  - Documentation: 'docs.md'
  - Operations:
    - 'Vagrant': 'ops/vagrant.md'
    - 'Docker': 'ops/docker.md'
    - 'Amazon': 'ops/amazon.md'
    - 'Azure': 'ops/azure.md'
  - "Mock and API Tools": 'tools.md'
  - 'Command Line': 'cmd/cmd.md'
- Learning:
  - 'Tutorials': 'learning/tutorials.md'
- Teaching: 
  - 'General': 'research.md'
  - 'Learning Systems': 'teaching/teach.md'
  - 'Class Tutorials':
    - 'Learning Sources': 'teaching/teach.md'
    - 'HTML and CSS':
      - 'Semantic HTML': 'teaching/html/semantic.md'
    - 'JavaScript': 
      - 'Intro': 'teaching/javascript/intro.md'
      - 'Classes':
        - 'Class 1': 'teaching/javascript/classes/class1.md'
