site_name: Development Notes for Johan Martin
repo_url: https://github.com/catenare/devnotes
site_description: Notes tracking for developing different apps.
site_author: Johan Martin (http://www.johan-martin.com)
repo_name: 'GitHub'
edit_uri: edit/master/md/
dev_addr: '127.0.0.1:8888'
strict: true
# docs_dir: 'md'
# site_dir: 'docs'
copyright: Johan Martin &copy; 2017
markdown_extensions:
  - pymdownx.tilde
theme: 'material'
pages:
- Home: 'index.md'
- Development:
  - Database: 
      - Postgresql: 'database.md'
      - Migrations: 'dbmigrations.md'
  - Web:
    - 'Basic Setup': 'web/page.md'
    - 'Front End': 
      - 'Static': 'web/static.md'
      - 'Front': 'web/front.md'
  - JavaScript:
    - 'General Notes': 'web/notes.md'
    - 'RxJs': 'web/javascript/rxjs.md'
  - PHP:
    - Resources: 'php/resources.md'
    - Composer: 'php/composer.md'
    - Wordpress:
      - 'Setup': 'php/wordpress/setup.md'
      - 'Home': 'php/wordpress/wordpress.md'
      - 'Plugin Dev': 'php/wordpress/plugin development.md'
      - 'Theme Dev': 'php/wordpress/themes.md'
  - 'Python': 
    - 'General': 'python/general.md'
    - 'Flask': 'python/flask.md'
    - 'Research': 'python/research.md'
  - 'Ruby': 'ruby.md'
  - 'Java': 'java.md'
  - Frameworks:
    - Spring: 'spring.md'
  - Version Control:
    - 'Git': 'git.md'
  - Mobile:
    - General: 'mobile/general.md'
    - Research: 'mobile/mobile.md'
    - 'Mobile Dev Notes': 'mobile/mobilenotes.md'
    - Ionic: 'mobile/ionic.md'
- "Content Management": 'cms.md'
- Tools:
  - Reporting: 'reporting.md'
  - Documentation: 'docs.md'
  - Operations:
    - 'Vagrant': 'ops/vagrant.md'
    - 'Docker': 'ops/docker.md'
    - 'Amazon': 'ops/amazon.md'
    - 'Azure': 'ops/azure.md'
  - "Mock and API Tools": 'tools.md'
  - 'Command Line': 'cmd/cmd.md'
- Research: 
  - 'General': 'research.md'
  - 'Learning Systems': 'teach.md'
- Learning:
  - Angular:
    - 'Learning Angular': 'learning/angular.md'
    - 'Wordpress API & Angular': 'learning/angular/wordpress.md'
