site_name: Development Notes for Johan Martin
repo_url: https://github.com/catenare/devnotes
repo_name: 'GitHub'
edit_uri: edit/master/md/
docs_dir: 'md'
site_dir: 'docs'
markdown_extensions:
  - pymdownx.tilde
theme: 'material'
pages:
- Home: 'index.md'
- Sections:
  - Database: 
      - Postgresql: 'database.md'
      - Migrations: 'dbmigrations.md'
  - Mobile:
    - 'Mobile Dev': 'mobile.md'
  - Languages:
    - 'PHP': 'php.md'
    - 'Python': 'python.md'
    - 'Ruby': 'ruby.md'
  - Frameworks:
    - 'Spring': 'spring.md'
  - Version Control:
    - 'Git': 'git.md'
  - 'Web Dev':
    - 'Front-End': 'front.md'
  - 'Other': 'other.md'

