site_name: Johan Martin's Developer Notebook
repo_url: https://github.com/catenare/devnotes
site_description: Too much to keep in my head!!!
site_url: https://devnotes.johan-martin.com
site_author: Johan Martin (http://www.johan-martin.com)
repo_name: "GitHub"
edit_uri: edit/master/docs/
dev_addr: "127.0.0.1:9090"
strict: true
# docs_dir: 'md'
# site_dir: 'docs'
copyright: Johan Martin &copy; 2019
markdown_extensions:
  - pymdownx.tilde
theme: "material"
extra_css:
  - css/extra.css
nav:
  - Home: "index.md"
  - Cloud:
    - AWS:
        - General: cloud/aws/general.md
        - Amplify: cloud/aws/amplify.md
        - "API Gateway": cloud/aws/api_gateway.md
        - "Cognito": cloud/aws/cognito.md
        - "DynamoDB": cloud/aws/dynamodb.md
        - "Lightsail": cloud/aws/lightsail.md
        - "Search": cloud/aws/search.md
    - Azure:
        - General: cloud/azure/general.md
    - Google:
        - Firebase:
            - "General": cloud/google/firebase/general.md
  - "Web Development":
    - Database:
        - Migrations:
            - General: web_development/database/migrations/general.md
        - Mongo: web_development/database/mongo.md
        - MySQL: web_development/database/mysql.md
        - Postgres: web_development/database/postgresql.md
    - WordPress:
        - Setup: web_development/wordpress/setup.md
  - Tools:
    - NodeJS:
        General: tools/nodejs/general.md
  - Resources:
    - PHP: resources/php.md
