site_name: Development Notes for Johan Martin
repo_url: https://github.com/catenare/devnotes
site_description: Notes tracking for developing different apps.
site_author: Johan Martin (http://www.johan-martin.com)
repo_name: 'GitHub'
edit_uri: edit/master/md/
# docs_dir: 'md'
# site_dir: 'docs'
copyright: Johan Martin &copy; 2017
markdown_extensions:
  - pymdownx.tilde
theme: 'material'
pages:
- Home: 'index.md'
- Development:
  - Database: 
      - Postgresql: 'database.md'
      - Migrations: 'dbmigrations.md'
  - Languages:
    - PHP: 
      - Setup: 'php/setup.md'
      - Composer: 'php/composer.md'
      - Wordpress:
        - 'Setup': 'php/wordpress/setup.md'
        - 'Home': 'php/wordpress/wordpress.md'
        - 'Plugin Dev': 'php/wordpress/plugin development.md'
    - 'Python': 'python.md'
    - 'Ruby': 'ruby.md'
  - Frameworks:
    - Spring: 'spring.md'
  - Version Control:
    - 'Git': 'git.md'
  - 'Front End': 'static.md'
  - Mobile:
    - Hybrid: 'ionic.md'
    - 'Mobile Dev': 'mobile.md'
- Reports: 'reporting.md'
- Documentation: 'docs.md'
- Operations:
  - 'Vagrant': 'vagrant.md'
  - 'Docker': 'docker.md'
- Tools: 'tools.md'
- 'Command Line': 'cmd/cmd.md'
- 'Learning Systems': 'teach.md'
- Research: 'research.md'


