site_name: Development Notes for Johan Martin
repo_url: https://github.com/catenare/devnotes
site_description: Notes tracking for developing different apps.
site_author: Johan Martin (http://www.johan-martin.com)
repo_name: 'GitHub'
edit_uri: edit/master/md/
dev_addr: '127.0.0.1:8888'
strict: true
# docs_dir: 'md'
# site_dir: 'docs'
copyright: Johan Martin &copy; 2017
markdown_extensions:
  - pymdownx.tilde
theme: 'material'
extra_css:
- css/extra.css
pages:
- Home: 'index.md'
- Projects:
  - Overview: 'projects/PaseoNetwork.md'
  - 'The Martin Family Site': 'projects/themartinssite.md'
- Development:
  - Wordpress:
    - 'Notes': 'php/wordpress/notes.md'
    - 'Admin': 'php/wordpress/admin.md'
    - 'Deployment': 'php/wordpress/deployment.md'
    - API:
      - API: 'php/wordpress/api/api.md'
      - 'Learn Wordpress REST API': 'php/wordpress/api/learn.md'
      - 'Angular': 'php/wordpress/api/angular.md'
      - 'Backbone': 'php/wordpress/api/backbonejs.md'
      - 'Vuejs': 'php/wordpress/api/vuejs.md'
    - 'Setup': 'php/wordpress/setup.md'
    - 'Local Dev': 'php/wordpress/dev.md'
    - 'Plugin Dev': 'php/wordpress/plugin development.md'
    - 'Dev from scratch': 'php/wordpress/plugin-dev-from-scratch.md'
    - 'Theme Dev': 'php/wordpress/themes.md'
  - Database: 
      - Migrations: 'database/dbmigrations.md'
      - Mongo: 'database/mongo.md'
      - Mysql: 'database/mysql.md'
      - Postgresql: 'database/postgresql.md'

  - Web:
    - 'Notes': 'web/notes.md'
    - 'Basic Setup': 'web/page.md'
    - 'Front End':
      - 'Front': 'web/front.md'
      - 'CSS': 'web/css.md'
      - 'Foundation': 'web/foundation.md'
      - 'Asset Management': 'web/assets.md'
    - 'Build Tools':
      - 'Webpack':
        - 'Notes': 'web/javascript/webpack/notes.md'
        - 'Configuration': 
          - 'Basic': 'web/javascript/webpack/webpack.md'
          - 'Html Webpack Plugin': 'web/javascript/webpack/html-webpack-plugin.md'
  - JavaScript:
    - 'General Notes': 'web/javascript/notes.md'
    - 'JS Starter Config': 'web/javascript/startup.md'
    - 'RxJs': 'web/javascript/rxjs.md'
    - 'Testing': 
      - 'Intro': 'web/javascript/testing/general.md'
      - 'Tape': 'web/javascript/testing/tape.md'
    - Angular:
      - 'Learning Angular': 'web/javascript/angular.md'
    - 'Vuejs':
      - 'Notes': 'web/javascript/vue/notes.md' 
      - 'Vuejs': 'web/javascript/vue/vuejs.md'
      - 'Vuejs Setup': 'web/javascript/vue/configuration.md'
      - 'Foundation Setup': 'web/javascript/vue/foundation.md'
    - Reactjs: 'web/javascript/reactjs/reactjs.md'
    - Webpack:
      - 'Build plugin or loader': 'web/javascript/webpack/Building a web pack plugin or loader.md'
      - 'Webpack Plugin': 'web/javascript/webpack/html-webpack-plugin.md'
      - 'Notes': 'web/javascript/webpack/notes.md'
      - 'Webpack': 'web/javascript/webpack/webpack.md'
  - PHP:
    - Resources: 'php/resources.md'
    - Composer: 'php/composer.md'
  - Python: 
    - 'General': 'python/general.md'
    - 'Packages': 'python/packages.md'
    - 'Research': 'python/research.md'
  - Ruby: 'ruby/ruby.md'
  - Java:
    - 'Notes': 'java/java.md'
    - 'JHipster': 'java/jhipster.md'
  - Nodejs:
    - 'Notes': 'nodejs/notes.md'
  - Frameworks:
    - Spring: 'spring.md'
  - Version Control:
    - 'Git': 'git.md'
  - Mobile:
    - General: 'mobile/general.md'
    - Research: 'mobile/mobile.md'
    - 'Mobile Dev Notes': 'mobile/mobilenotes.md'
    - Ionic: 'mobile/ionic.md'
- "Content Management": 'cms.md'
- Tools:
  - Reporting: 'reporting.md'
  - Documentation: 'docs.md'
  - Operations:
    - 'Vagrant': 'ops/vagrant.md'
    - 'Docker': 'ops/docker.md'
    - 'Amazon': 'ops/amazon.md'
    - 'Azure': 'ops/azure.md'
  - "Mock and API Tools": 'tools.md'
  - 'Command Line': 'cmd/cmd.md'
- Work: 'work/employment.md'
- Learning:
  - 'Wordpress Rest API': 'php/wordpress/api/learn.md'
  - 'Tutorials': 'learning/tutorials.md'
- Teaching: 
  - 'General': 'research.md'
  - 'Learning Systems': 'teaching/teach.md'
  - 'OpenEdx':
    - 'Notes': 'teaching/openedx/openedx.md'
  - 'Class Tutorials':
    - 'Learning Sources': 'teaching/teach.md'
    - 'HTML and CSS':
      - 'Semantic HTML': 'teaching/html/semantic.md'
    - 'JavaScript': 
      - 'Intro': 'teaching/javascript/intro.md'
      - 'Classes':
        - 'Class 1': 'teaching/javascript/classes/class1.md'
      - 'Tutorials':
        - 'Prototyping With Vue and Marvel': 'teaching/javascript/tutorials/prototypewithvue.md'
- Misc:
  - Notes: 'misc/notes.md'
