site_name: Development Notes for Johan Martin
repo_url: https://github.com/catenare/devnotes
site_description: Notes tracking for developing different apps.
site_author: Johan Martin (http://www.johan-martin.com)
repo_name: 'GitHub'
edit_uri: edit/master/md/
dev_addr: '127.0.0.1:8888'
strict: true
# docs_dir: 'md'
# site_dir: 'docs'
copyright: Johan Martin &copy; 2017
markdown_extensions:
  - pymdownx.tilde
theme: 'material'
extra_css:
- css/extra.css
pages:
- Home: 'index.md'
- Development:
  - Cloud:
    - 'AWS': 
      - 'Amazon': 'cloud/aws/aws.md'
      - 'Cognito': 'cloud/aws/cognito.md'
    - 'Google':
      - 'Google': "cloud/google/google.md"
  - Wordpress:
    - 'Notes': 'php/wordpress/notes.md'
    - 'Admin': 'php/wordpress/admin.md'
    - 'Deployment': 'php/wordpress/deployment.md'
    - API:
      - API: 'php/wordpress/api/api.md'
      - 'Learn Wordpress REST API': 'php/wordpress/api/learn.md'
      - 'Angular': 'php/wordpress/api/angular.md'
      - 'Backbone': 'php/wordpress/api/backbonejs.md'
      - 'Vuejs': 'php/wordpress/api/vuejs.md'
    - 'Setup': 'php/wordpress/setup.md'
    - 'Local Dev': 'php/wordpress/dev.md'
    - 'Plugin Dev': 'php/wordpress/plugin development.md'
    - 'Dev from scratch': 'php/wordpress/plugin-dev-from-scratch.md'
    - 'Theme Dev': 'php/wordpress/themes.md'
  - Database: 
      - Migrations: 
        - General: 'database/dbmigrations.md'
        - FlyWay: 'database/flyway.md'
      - Mongo: 'database/mongo.md'
      - Mysql: 'database/mysql.md'
      - Postgresql: 'database/postgresql.md'
  - 'Front End':
    - 'Basics':
      - 'Front': 'web/front.md'
      - 'CSS': 'web/css.md'
      - 'Foundation': 'web/foundation.md'
      - 'Asset Management': 'web/assets.md'
      - 'Notes': 'web/notes.md'
      - 'StyleGuide': 'web/styleguide.md'
      - 'Colors': 'process.md'
    - 'General Notes': 'web/javascript/notes.md'
    - 'JS Starter Config': 'web/javascript/startup.md'
    - 'RxJs': 'web/javascript/rxjs.md'
    - TypeScript: 'web/typescript.md'
    - 'Testing': 
      - 'Intro': 'web/javascript/testing/general.md'
      - 'Tape': 'web/javascript/testing/tape.md'
    - Angular:
      - 'Angular': 'web/javascript/Angular/angular.md'
    - 'Vuejs':
      - 'Notes': 'web/javascript/vue/notes.md' 
      - 'Vue': 'web/javascript/vue/vuejs.md'
      - 'Foundation Setup': 'web/javascript/vue/foundation.md'
    - Reactjs: 'web/javascript/reactjs/reactjs.md'
    - Redux: 'web/javascript/reactjs/redux.md'
    - Webpack:
      - 'Webpack': 'web/javascript/webpack/webpack.md'
      - 'Notes': 'web/javascript/webpack/notes.md'
  - PHP:
    - Resources: 'php/resources.md'
    - Composer: 'php/composer.md'
  - Python: 
    - 'General': 'python/general.md'
    - 'Packages': 'python/packages.md'
    - 'Research': 'python/research.md'
    - 'Flask': 'python/flask.md'
    - 'SQLAlchemy': 'python/sqlalchemy.md'  
  - Ruby: 'ruby/ruby.md'
  - Java:
    - 'Notes': 'java/java.md'
    - 'Spring': 'java/spring.md'
    - 'JHipster': 'java/jhipster.md'
  - Nodejs:
    - 'Notes': 'nodejs/notes.md'
  - Version Control:
    - 'Git': 'git.md'
  - Mobile:
    - General: 'mobile/general.md'
    - Research: 'mobile/mobile.md'
    - 'Mobile Dev Notes': 'mobile/mobilenotes.md'
    - Ionic: 'mobile/ionic.md'
- "Content Management": 'cms.md'
- Tools:
  - Reporting: 'reporting.md'
  - Documentation: 'docs.md'
  - Operations:
    - 'Local': 'ops/local.md'
    - 'Vagrant': 'ops/vagrant.md'
    - 'Docker': 'ops/docker.md'
    - 'Amazon': 'ops/amazon.md'
    - 'Azure': 'ops/azure.md'
  - "Mock and API Tools": 'tools.md'
  - 'Command Line': 'cmd/cmd.md'
- Work: 'work/employment.md'
- Learning:
  - 'Wordpress Rest API': 'php/wordpress/api/learn.md'
  - 'Tutorials': 'learning/tutorials.md'
- Teaching: 
  - 'General': 'research.md'
  - 'Tools': 'teaching/tools.md'
  - 'Custom Modules': 'teaching/modules.md'
  - 'OpenEdx':
    - 'Notes': 'teaching/openedx/openedx.md'
  - 'Class Tutorials':
    - 'HTML and CSS':
      - 'Semantic HTML': 'teaching/html/semantic.md'
    - 'JavaScript': 
      - 'Intro': 'teaching/javascript/intro.md'
      - 'Classes':
        - 'Class 1': 'teaching/javascript/classes/class1.md'
      - 'Tutorials':
        - 'Prototyping With Vue and Marvel': 'teaching/javascript/tutorials/prototypewithvue.md'
- Misc:
  - 'House related': 'misc/house.md'
  - 'Visual StoryTelling/Sketchnotes': 'misc/sketch.md'
